/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 6 to 6

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char player[] =
{
  0x00,0x3C,0x00,0x3A,0x3C,0x14,0x30,0x0C,
  0xA5,0x7E,0x3C,0x3C,0x3C,0x3C,0x24,0x24
};

/* End of EXPORT.C */
