/*

 INVENTORY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\barry\Desktop\Creating stuffs\Game Dev\GB development\TerrariaGB\src\invtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define inventorytilemapWidth 20
#define inventorytilemapHeight 18
#define inventorytilemapBank 0

extern unsigned char inventorytilemap[];

/* End of INVENTORY.H */
