/*

 LOADINGSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\barry\Desktop\Creating stuffs\Game Dev\GB development\TerrariaGB\src\Titlescreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define loadingWidth 20
#define loadingHeight 18
#define loadingBank 0

extern unsigned char loading[];

/* End of LOADINGSCREEN.H */
